apiVersion: v1
kind: ConfigMap
metadata:
  name: bookmarker-config
data:
  postgres_host: postgres
  postgres_dbname: bookmarkerdb
  postgres_port: "5432"

---

apiVersion: v1
kind: Secret
metadata:
  name: bookmarker-secrets
type: Opaque
data:
  postgres_password: cGFzc2Ri
  postgres_username: dXNlcmRi