apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bookmarker-api-service-monitor
  labels:
    release: "kube-prometheus-stack"
spec:
  endpoints:
    - port: http
      interval: 30s
      scrapeTimeout: 10s
      path: "/actuator/prometheus"
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: bookmarker-api-pod
