# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ "**" ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bookmarker-api

    steps:
    - uses: actions/checkout@v3

    - name: Get version
      id: get_version
      run: echo "::set-output name=VERSION::$(grep "version = " build.gradle | awk '{print $3}' | tr -d \'\" )"

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v0

    - name: Build with Gradle
      run: ./gradlew clean build jibDockerBuild --no-daemon

    # - name: Push to Docker Hub
    #   uses: docker/build-push-action@v2
    #   with:
    #     username: ${{ secrets.DOCKER_USERNAME }}
    #     password: ${{ secrets.DOCKER_PASSWORD }}
    #     repository: ${{ secrets.DOCKER_USERNAME }}/bookmarker-api
    #     tags: 2.0.0, latest