name: Compile and Push to Docker Hub

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:

  build-and-push-to-dockerhub:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bookmarker-api

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v0

    - name: Build with Gradle
      run: ./gradlew clean jibDockerBuild --no-daemon
    
    - name: Get version
      id: get-ms-version
      run: |
        ms_version=$(echo "$(grep "version = " build.gradle | awk '{print $3}' | tr -d \'\" )")
        echo version=$ms_version >> $GITHUB_OUTPUT

    - if: ${{ github.ref == 'refs/heads/master' }}
      name: Publish Docker Image
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/bookmarker-api:${{ steps.get-ms-version.outputs.version }}
