name: Compile and Push to Docker Hub

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bookmarker-api

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
    
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v0

    - name: Build with Gradle
      run: ./gradlew clean jibDockerBuild --no-daemon

    - name: Get version
      id: get-version
      run: |
          echo "VERSION=$(grep "version = " build.gradle | awk '{print $3}' | tr -d \'\" )" >> $GITHUB_ENV
  
  push:
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./bookmarker-api
 
    steps:
    - if: ${{ github.ref == 'refs/heads/master' }}
      name: Build and Publish Docker Image
      run: |
        ./mvnw clean package jib:dockerBuild -DskipTests
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/bookmarker-api:6.0
